In [74]:
import os

In [75]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [76]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

In [77]:
df=pd.read_csv(r'C:\Users\mayur\OneDrive\Desktop\data science training\project\medical\data\clean_medical.csv')

In [78]:
df


,Unnamed: 0,Gender,Smoking,Alcohol,PhysicalActivity,FamilyHistory,Disease,Age,BMI,BloodPressure,GlucoseLevel,Cholesterol,HeartRate
0,0,1,0,1,1,0,1,23,17.5,102,177,161,88
1,1,1,0,1,2,1,2,69,31.1,118,256,147,92
2,2,2,1,1,1,0,1,61,31.3,114,206,193,74
3,3,2,0,1,3,0,1,47,23.9,105,162,253,68
4,4,1,0,2,2,0,1,47,28.3,148,121,280,84
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9995,1,0,1,2,0,3,49,27.1,177,183,268,59
9996,9996,1,0,2,2,1,3,84,29.2,142,215,145,77
9997,9997,1,0,1,1,1,3,41,22.8,177,265,133,71
9998,9998,1,0,1,1,1,2,55,29.0,126,241,298,57


In [79]:
print(df['Disease'].value_counts())

Disease
1    6329
3    1771
2    1453
4     232
5     215
Name: count, dtype: int64


In [80]:
df.drop('Unnamed: 0', axis=1, inplace=True)

In [81]:
x=df.drop('Disease',axis=1)

In [82]:
y=df[['Disease']]

In [83]:
x

,Gender,Smoking,Alcohol,PhysicalActivity,FamilyHistory,Age,BMI,BloodPressure,GlucoseLevel,Cholesterol,HeartRate
0,1,0,1,1,0,23,17.5,102,177,161,88
1,1,0,1,2,1,69,31.1,118,256,147,92
2,2,1,1,1,0,61,31.3,114,206,193,74
3,2,0,1,3,0,47,23.9,105,162,253,68
4,1,0,2,2,0,47,28.3,148,121,280,84
...,...,...,...,...,...,...,...,...,...,...,...
9995,1,0,1,2,0,49,27.1,177,183,268,59
9996,1,0,2,2,1,84,29.2,142,215,145,77
9997,1,0,1,1,1,41,22.8,177,265,133,71
9998,1,0,1,1,1,55,29.0,126,241,298,57


In [84]:
y

,Disease
0,1
1,2
2,1
3,1
4,1
...,...
9995,3
9996,3
9997,3
9998,2


In [85]:
print(df["Disease"].unique())

[1 2 3 4 5]


In [86]:
print(df["Disease"].value_counts())

Disease
1    6329
3    1771
2    1453
4     232
5     215
Name: count, dtype: int64


In [87]:
print(df["Disease"].value_counts())

Disease
1    6329
3    1771
2    1453
4     232
5     215
Name: count, dtype: int64


In [88]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [89]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
from sklearn.svm import SVC
sv=SVC()
sv.fit(x_train,y_train)
print("svc training",sv.score(x_train,y_train))
print("svc testing",sv.score(x_test,y_test))

c:\Users\mayur\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:1352: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


svc training 0.63125
svc testing 0.6395


In [90]:
log=LogisticRegression()
log.fit(x_train,y_train)
print("log training",log.score(x_train,y_train))
print("log testing",log.score(x_test,y_test))

log training 0.630625
log testing 0.6395


c:\Users\mayur\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:1352: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\Users\mayur\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [91]:
from sklearn.tree import DecisionTreeClassifier

dt = DecisionTreeClassifier(
    max_depth=5,
    min_samples_split=10,
    min_samples_leaf=5,
    random_state=42
)

dt.fit(x_train, y_train)

,"criterion criterion: {""gini"", ""entropy"", ""log_loss""}, default=""gini""The function to measure the quality of a split. Supported criteria are""gini"" for the Gini impurity and ""log_loss"" and ""entropy"" both for theShannon information gain, see :ref:`tree_mathematical_formulation`.",'gini'
,"splitter splitter: {""best"", ""random""}, default=""best""The strategy used to choose the split at each node. Supportedstrategies are ""best"" to choose the best split and ""random"" to choosethe best random split.",'best'
,"max_depth max_depth: int, default=NoneThe maximum depth of the tree. If None, then nodes are expanded untilall leaves are pure or until all leaves contain less thanmin_samples_split samples.",5
,"min_samples_split min_samples_split: int or float, default=2The minimum number of samples required to split an internal node:- If int, then consider `min_samples_split` as the minimum number.- If float, then `min_samples_split` is a fraction and `ceil(min_samples_split * n_samples)` are the minimum number of samples for each split... versionchanged:: 0.18 Added float values for fractions.",10
,"min_samples_leaf min_samples_leaf: int or float, default=1The minimum number of samples required to be at a leaf node.A split point at any depth will only be considered if it leaves atleast ``min_samples_leaf`` training samples in each of the left andright branches. This may have the effect of smoothing the model,especially in regression.- If int, then consider `min_samples_leaf` as the minimum number.- If float, then `min_samples_leaf` is a fraction and `ceil(min_samples_leaf * n_samples)` are the minimum number of samples for each node... versionchanged:: 0.18 Added float values for fractions.",5
,"min_weight_fraction_leaf min_weight_fraction_leaf: float, default=0.0The minimum weighted fraction of the sum total of weights (of allthe input samples) required to be at a leaf node. Samples haveequal weight when sample_weight is not provided.",0.0
,"max_features max_features: int, float or {""sqrt"", ""log2""}, default=NoneThe number of features to consider when looking for the best split:- If int, then consider `max_features` features at each split.- If float, then `max_features` is a fraction and `max(1, int(max_features * n_features_in_))` features are considered at each split.- If ""sqrt"", then `max_features=sqrt(n_features)`.- If ""log2"", then `max_features=log2(n_features)`.- If None, then `max_features=n_features`... note:: The search for a split does not stop until at least one valid partition of the node samples is found, even if it requires to effectively inspect more than ``max_features`` features.",None
,"random_state random_state: int, RandomState instance or None, default=NoneControls the randomness of the estimator. The features are alwaysrandomly permuted at each split, even if ``splitter`` is set to``""best""``. When ``max_features < n_features``, the algorithm willselect ``max_features`` at random at each split before finding the bestsplit among them. But the best found split may vary across differentruns, even if ``max_features=n_features``. That is the case, if theimprovement of the criterion is identical for several splits and onesplit has to be selected at random. To obtain a deterministic behaviourduring fitting, ``random_state`` has to be fixed to an integer.See :term:`Glossary ` for details.",42
,"max_leaf_nodes max_leaf_nodes: int, default=NoneGrow a tree with ``max_leaf_nodes`` in best-first fashion.Best nodes are defined as relative reduction in impurity.If None then unlimited number of leaf nodes.",None
,"min_impurity_decrease min_impurity_decrease: float, default=0.0A node will be split if this split induces a decrease of the impuritygreater than or equal to this value.The weighted impurity decrease equation is the following:: N_t / N * (impurity - N_t_R / N_t * right_impurity - N_t_L / N_t * left_impurity)where ``N`` is the total number of samples, ``N_t`` is the number ofsamples at the current n

In [92]:
# from sklearn.tree import DecisionTreeClassifier
# # x,y=loan_approved(return_X_y=True)
# x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
# dt=DecisionTreeClassifier()
# dt.fit(x_train,y_train)

In [93]:
print("dt training",dt.score(x_train,y_train))
print("dt testing",dt.score(x_test,y_test))

dt training 0.667375
dt testing 0.6555


In [94]:
import joblib
joblib.dump(dt,"dt_load.lb")

['dt_load.lb']

In [95]:
from sklearn.ensemble import RandomForestClassifier

rfc = RandomForestClassifier(
    n_estimators=100,
    max_depth=5,
    min_samples_split=10,
    min_samples_leaf=5,
    class_weight='balanced',
    random_state=42
)

In [96]:

rfc.fit(x_train, y_train)

print("Train:", rfc.score(x_train, y_train))
print("Test:", rfc.score(x_test, y_test))

c:\Users\mayur\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\base.py:1336: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)


Train: 0.687625
Test: 0.64


In [97]:
import joblib
joblib.dump(rfc,"rfc_load.lb")

['rfc_load.lb']

In [98]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier()
rf.fit(x_train, y_train)

print("Train:", rf.score(x_train, y_train))
print("Test:", rf.score(x_test, y_test))

c:\Users\mayur\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\base.py:1336: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)


Train: 1.0
Test: 0.6745


In [99]:
print(model.classes_)

[1 2 3 4 5]


In [102]:
import joblib

model = joblib.load(r"C:\Users\mayur\OneDrive\Desktop\data science training\project\medical\model\rfc_load.lb")
print(model.classes_)

[1 2 3 4 5]
